#!/bin/sh

# Math util functions

calc() {
  local formula="$1"
  local format="$2"
  echo "${@:3:$#-2}" | awk -v format="${format}" '
    function ceil(x) {
      return x%1 ? int(x)+1 : x
    }
    function log2(x) {
      return log(x)/log(2)
    }
    function max2(x,y) {
      return x > y ? x : y
    }
    function round(x) {
      return int(x + 0.5)
    }
    {printf format,'"${formula}"'}
  '
}

int() {
  echo "$(calc "$1" "%d\n" "${@:2:$#-1}")"
}
